[build]
builder = "NIXPACKS"
buildCommand = "turbo build --filter=server"
watchPatterns = ["!/apps/web/**"]

[deploy]
numReplicas = 1
startCommand = "cd apps/server/ && npm run db:generate && npm run start"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10